version: '3.8'

services:
  postgres:
    container_name: energy-bill-tracker-postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: energy_bill_tracker
    volumes:
      - ./data:/var/lib/postgresql/data
